New tx fee estimation
ElrondNetwork/elrond-sdk pull request #150
Opened 2021-01-15 11:38 UTC by ccorcoveanu

This should only be review after #97 is merged

2021-01-15 16:06 UTC, andreibancioiu approved these changes

2021-01-18 10:17 UTC, AdoAdoAdo requested changes

2021-01-18 10:17 UTC, AdoAdoAdo commented on erdjs/src/transaction.spec.ts
> +    it("computes correct fee", () => {
maybe add a test with data field as well.

2021-01-18 21:22 UTC, ccorcoveanu commented on erdjs/src/networkParams.ts
> +        if (value <= 0) {
Yes, done

2021-01-18 21:34 UTC, ccorcoveanu commented on erdjs/src/transaction.spec.ts
> +    it("computes correct fee", () => {
done

2021-01-19 07:24 UTC, AdoAdoAdo approved these changes

2021-01-20 07:56 UTC, andreibancioiu approved these changes

2021-01-20 13:11 UTC, merged