sign tx with hash functionality for hw provider
ElrondNetwork/elrond-sdk pull request #217
Opened 2021-03-02 15:04 UTC by bogdan-rosianu

2021-03-04 20:58 UTC, andreibancioiu submitted a review, later dismissed

2021-03-04 20:58 UTC, andreibancioiu commented on erdjs/src/dapp/hwProvider.ts
> +    private async shouldSignWithHash(): Promise<boolean> {
:+1:

2021-03-04 20:58 UTC, andreibancioiu commented on erdjs/src/dapp/hwProvider.ts
> +            throw new Error("HWApp not initialised, call init() first");
You can also define specific errors in `errors.ts` - not necessarily in this case, but in general. Fine as it is.

2021-03-04 20:58 UTC, andreibancioiu commented on erdjs/src/dapp/hwProvider.ts
> +        const config = await this.hwApp.getAppConfiguration();
`await this.getAppVersion()` (new function) - optional.

2021-03-04 20:59 UTC, andreibancioiu commented
Please add a description to the PR - when making releases, we'll point to the this PR in the changelog file.

2021-03-11 10:05 UTC, ccorcoveanu requested changes

2021-03-11 21:04 UTC, bogdan-rosianu commented on erdjs/src/dapp/common.ts
> +        if (diff < 0) {
done

2021-03-11 21:04 UTC, bogdan-rosianu commented on erdjs/src/dapp/common.ts
> +    const l = Math.min(segmentsA.length, segmentsB.length);
done

2021-03-11 21:04 UTC, bogdan-rosianu commented on erdjs/src/dapp/common.ts
> +export function isLedgerVersionForSigningUsingHash(version: string) : boolean {
done

2021-03-12 09:17 UTC, ccorcoveanu approved these changes

2021-03-12 09:39 UTC, andreibancioiu approved these changes

2021-03-12 16:22 UTC, merged