Development
ElrondNetwork/elrond-sdk pull request #231
Opened 2021-03-16 21:26 UTC by ccorcoveanu

2021-03-18 18:47 UTC, andreibancioiu approved these changes

2021-03-22 08:36 UTC, camilbancioiu requested changes

2021-03-22 08:36 UTC, camilbancioiu commented on erdpy/delegation/staking_provider.py
> +        data += '@' + binascii.hexlify(str.encode('true')).decode()
`hexlify` is not needed here at all. Please do the following instead:
```suggestion
        data += '@' + 'true'.encode('ascii').hex()
```

2021-03-22 08:36 UTC, camilbancioiu commented on erdpy/delegation/staking_provider.py
> +        data += '@' + binascii.hexlify(str.encode('false')).decode()
```suggestion
        data += '@' + 'false'.encode('ascii').hex()
```

2021-03-22 08:39 UTC, camilbancioiu approved these changes

2021-03-22 08:40 UTC, andreibancioiu approved these changes

2021-03-22 08:42 UTC, merged